### ISSUE TITLE
Fork Yuno for Phase II

### ISSUE THREAD

**Issue by jakemco** [bulatb/yuno#11]
We should fork Yuno for Phase II and write a new test suite. Here's my idea:

For each test, you have to write two files, `testname.c` and `testname.rc` and they should be equivalent.

Additionally, in Yuno's config, you can specify a username and server to ssh into before running (so that I can work locally, but it will run the tests on ieng9).

Then Yuno will run the local RC compiler on the rc file, then scp over the .c and the .s file, then compile them remotely, and run then, comparing their output.

The basic flow (in bash) being

``` bash
$ ./RC testname.rc
$ scp rc.s user@ieng9
$ scp testname.c user@ieng9
$ ssh user@ieng9 'gcc input.c output.s rc.s; ./a.out' > RC_OUT
$ ssh user@ieng9 'gcc input.c output.s testname.c; ./a.out' > C_OUT
$ diff RC_OUT C_OUT
```

What you thinks?

**Comment by bulatb** [comment]
Done. :)
